### ISSUE TITLE
Drop php-5.x supports

### ISSUE THREAD

**Issue by peter279k** [Maikuolan/Common#5]
As title, I think it's time to drop `php-5.x` supports because these versions has been deprecated for about long time.

We should let this package require `php-7.1` version at least.

**Comment by Maikuolan** [comment]
Definitely. :-)

When we drop support for PHP 5x, the next versioned release for the Common Classes Package should be `v2.0.0` (because IMO, upping the minimum required PHP version, is a backwards-incompatible change, and the package adheres to SemVer, and SemVer requires that new releases containing backwards-incompatible changes should be major version releases).

The reason that I've opted to support from PHP >= 5.4 for v1, is because the first two classes in the package (L10N and YAML) were originally built for CIDRAM and phpMussel, which currently support PHP >= 5.4 (so, my thinking was that, in order to maintain minimum PHP version requirement consistency, that the Common Classes Package v1 should also support at least PHP >= 5.4). I plan on upping the minimum required PHP version for both CIDRAM and phpMussel to PHP >= 7.2 in the very near future though (when CIDRAM v2 and phpMussel v2 are released), so, there won't be any problems with version consistency at that point anyway.

My current thinking is that I could release a v2 for all three packages around the same time, pending no unforeseen problems.

**Comment by peter279k** [comment]
Hi @Maikuolan, thank you for your reply.

I glad you can do this after upgrading these package versions.

Thank you for your answer and concern again!

**Comment by Maikuolan** [comment]
The package has been branched (we now have distinct v1 and v2 branches). I'll make a start on dropping 5x support for v2 soon.

**Comment by peter279k** [comment]
Please add the notice in `README`.

And it can let us know about the released version.

**Comment by Maikuolan** [comment]
> Please add the notice in `README`.
>
> And it can let us know about the released version.

Done (92615c327ade6b6ab218173a3ca6cff7f10c206d). :-)

**Comment by Maikuolan** [comment]
Marking as implemented and closing.
